### ISSUE TITLE
adapter刷新数据布局错乱

### ISSUE THREAD

**Issue by doudou199291** [xiangcman/LayoutManager-FlowLayout#15]
Vivo X20上,点击添加数据之后,点击adapter整体刷新数据,布局会错乱,使用的是1.6版本;

**Comment by xiangcman** [comment]
我这边验证过你的问题，整体刷新是不会出现你说的错乱问题(事例代码):
list.add(0,new ShowItem("新增的1"));
list.add(0,new ShowItem("新增的2"));
list.add(0,new ShowItem("新增的3"));
flowAdapter.notifyDataSetChanged();

**Comment by doudou199291** [comment]
添加之后我更改为直接setadapter就正常;
